I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 5, in script
    define aright = position(xalign=0.2)
  File "game/script.rpy", line 5, in <module>
    define aright = position(xalign=0.2)
TypeError: __new__() got an unexpected keyword argument 'xalign'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 5, in script
    define aright = position(xalign=0.2)
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 2248, in execute
    self.set()
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 2262, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Hina\Documents\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 5, in <module>
    define aright = position(xalign=0.2)
TypeError: __new__() got an unexpected keyword argument 'xalign'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
MentalHealthVN 1.0
Thu May 29 22:45:47 2025
